### ISSUE TITLE
compatibility with Mongo.Collection (patch included)

### ISSUE THREAD

**Issue by krawalli** [msavin/MongoInspector#12]
Hi,

here is a little patch for 
1) Mongo.Collection support 
2) and give local (client only) collections (those who are initiated with "null" ) a name
Test with:

~~~javascript
LocalCol = new Mongo.Collection(null, {label: 'MyName'});
AnotherLocal = new Mongo.Collection(null);
~~~

This should show up as 
- _MyName
- _local_
in the list. The underscore (__) should mark local only collections. If no label is given, _local_ is used as name.

_Please give it a try_.

If you still get those "use new for Mongo.Collection" you should change the loading order of the package in your .meteor/packages files (don't forget to stop your meteor before editing)

###Patch:
in mongoinspector_body.js replace the part for initialization with:
~~~javascript
// ...

/*
 var MongoInspector_origCollection = Mongo.Collection,
        MongoInspector_activeCollections = [],
        MongoInspector_activeCollectionDep = new Tracker.Dependency;

    Meteor.Collection = function (name, options) {
        var instance = new MongoInspector_origCollection(name, options);
    
        MongoInspector_activeCollections.push({
            name: name,
            instance: instance
        });
        MongoInspector_activeCollectionDep.changed();
    
        return instance;
    };
*/

var MongoInspector_origCollection = Mongo.Collection,
  MongoInspector_activeCollections = [],
  MongoInspector_activeCollectionDep = new Tracker.Dependency;

Mongo.Collection = function () {
  MongoInspector_origCollection.apply(this, arguments);
  var label, name;
  if (arguments.length === 2 && arguments[1]) {
    label = arguments[1].label;
  }
  label = label || 'local_';
  name = arguments[0] || '_' + label;
  MongoInspector_activeCollections.push({
    name: name,
    instance: this
  });
  MongoInspector_activeCollectionDep.changed();

  return this;
};

Mongo.Collection.prototype = Object.create(MongoInspector_origCollection.prototype);

for (var func in MongoInspector_origCollection) {
  if (MongoInspector_origCollection.hasOwnProperty(func)) {
    Mongo.Collection[func] = MongoInspector_origCollection[func];
  }
}
// ...
~~~~

**Comment by msavin** [comment]
Wow - thanks man. Going to try it out tonight and let you know what happens.

**Comment by msavin** [comment]
I tried your patch in the core package application (this repo) but it did not work. 

From the console: 

> [Log] Exception in template helper: MongoInspector_collections@http://localhost:5000/packages/msavin_mongoinspector.js?f2fd3113651d1b54c20f43b562647a90fae3ce8d:362:47 (meteor.js, line 883)
http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:2693:21
http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1602:21
call@http://localhost:5000/packages/spacebars.js?3c496d2950151d744a8574297b46d2763a123bdf:169:23
http://localhost:5000/packages/msavin_mongoinspector.js?f2fd3113651d1b54c20f43b562647a90fae3ce8d:48:26
http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:2503:34
http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1795:20
_withCurrentView@http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:2029:16
viewAutorun@http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1794:34
_compute@http://localhost:5000/packages/tracker.js?192a05cc46b867dadbe8bf90dd961f6f8fd1574f:288:36
Computation@http://localhost:5000/packages/tracker.js?192a05cc46b867dadbe8bf90dd961f6f8fd1574f:206:18
autorun@http://localhost:5000/packages/tracker.js?192a05cc46b867dadbe8bf90dd961f6f8fd1574f:476:34
autorun@http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1793:26
http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:2502:21
fireCallbacks@http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1822:20
nonreactive@http://localhost:5000/packages/tracker.js?192a05cc46b867dadbe8bf90dd961f6f8fd1574f:502:13
http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1819:24
_withCurrentView@http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:2029:16
_fireCallbacks@http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1818:25
_createView@http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1836:23
_materializeView@http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1840:20
visitObject@http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1508:44
visit@http://localhost:5000/packages/htmljs.js?539b5fc23cf5e63bc8e324543a1026b138316a8c:118:36
visitArray@http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1412:17
visit@http://localhost:5000/packages/htmljs.js?539b5fc23cf5e63bc8e324543a1026b138316a8c:116:37
visitTag@http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1490:41
visit@http://localhost:5000/packages/htmljs.js?539b5fc23cf5e63bc8e324543a1026b138316a8c:103:37
doMaterialize@http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1858:48
nonreactive@http://localhost:5000/packages/tracker.js?192a05cc46b867dadbe8bf90dd961f6f8fd1574f:502:13
doRender@http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1856:26
http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1795:20
_withCurrentView@http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:2029:16
viewAutorun@http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1794:34
_compute@http://localhost:5000/packages/tracker.js?192a05cc46b867dadbe8bf90dd961f6f8fd1574f:288:36
Computation@http://localhost:5000/packages/tracker.js?192a05cc46b867dadbe8bf90dd961f6f8fd1574f:206:18
autorun@http://localhost:5000/packages/tracker.js?192a05cc46b867dadbe8bf90dd961f6f8fd1574f:476:34
autorun@http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1793:26
http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1847:17
nonreactive@http://localhost:5000/packages/tracker.js?192a05cc46b867dadbe8bf90dd961f6f8fd1574f:502:13
_materializeView@http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1846:22
visitObject@http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1508:44
visit@http://localhost:5000/packages/htmljs.js?539b5fc23cf5e63bc8e324543a1026b138316a8c:118:36
visitArray@http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1412:17
visit@http://localhost:5000/packages/htmljs.js?539b5fc23cf5e63bc8e324543a1026b138316a8c:116:37
doMaterialize@http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1858:48
nonreactive@http://localhost:5000/packages/tracker.js?192a05cc46b867dadbe8bf90dd961f6f8fd1574f:502:13
doRender@http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1856:26
http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1795:20
_withCurrentView@http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:2029:16
viewAutorun@http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1794:34
_compute@http://localhost:5000/packages/tracker.js?192a05cc46b867dadbe8bf90dd961f6f8fd1574f:288:36
Computation@http://localhost:5000/packages/tracker.js?192a05cc46b867dadbe8bf90dd961f6f8fd1574f:206:18
autorun@http://localhost:5000/packages/tracker.js?192a05cc46b867dadbe8bf90dd961f6f8fd1574f:476:34
autorun@http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1793:26
http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1847:17
nonreactive@http://localhost:5000/packages/tracker.js?192a05cc46b867dadbe8bf90dd961f6f8fd1574f:502:13
_materializeView@http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:1846:22
render@http://localhost:5000/packages/blaze.js?77c0809654ee3a10dcd5a4f961fb1437e7957d33:2128:25
renderToDocument@http://localhost:5000/packages/templating.js?599ba307216da826d8b335332ebcc9a497a369a0:107:26
runStartupCallbacks@http://localhost:5000/packages/meteor.js?61916b1060b33931a21f104fbffb67c2f3d493c5:780:22
ready@http://localhost:5000/packages/meteor.js?61916b1060b33931a21f104fbffb67c2f3d493c5:782:22

If you'd like to fork it, I'd be happy to merge it into the main package.

**Comment by msavin** [comment]
I fixed that issue after renaming Inspector to MongoInspector.. the next error I'm getting is: 

[Error] Error: use "new" to construct a Mongo.Collection (mongo.js, line 121)

MongoInspector is the last package to load in my .packages file

**Comment by krawalli** [comment]
> If you still get those "use new for Mongo.Collection" you should change the loading order of the package in your .meteor/packages files (don't forget to stop your meteor before editing)

Move it up in package list. There are many other packages around which are causing that message. For me its rather at the top

**Comment by msavin** [comment]
Ah yes - its working normally for some reason now.  I've just played with it, I noticed the issue happens when I use Meteor.Collections(). When all of them are renamed to Mongo.Collections(), it seems to work fine. Maybe that could be a clue to the issue. Going to test it out a little more and merge it in :)

**Comment by krawalli** [comment]
Maybe you need a second class initialization code, but this time for Meteor.Collection.

**Comment by jonjamz** [comment]
Try something like this @msavin. It's untested but it might work.

```javascript
var MongoInspector_supportedCollections = [Meteor.Collection, Mongo.Collection],
  MongoInspector_activeCollections = [],
  MongoInspector_activeCollectionDep = new Tracker.Dependency;

// Iterate through supported collections, wrapping each for tracking...
for (var i = 0; i < 2; i++) {
  var orig = MongoInspector_supportedCollections[i];

  if (orig) {

    MongoInspector_supportedCollections[i] = function () {
      orig.apply(this, arguments);
      var label, name;
      if (arguments.length === 2 && arguments[1]) {
        label = arguments[1].label;
      }
      label = label || 'local_';
      name = arguments[0] || '_' + label;
      MongoInspector_activeCollections.push({
        name: name,
        instance: this
      });
      MongoInspector_activeCollectionDep.changed();

      return this;
    };

    MongoInspector_supportedCollections[i].prototype = Object.create(orig.prototype);

    for (var func in orig) {
      if (orig.hasOwnProperty(func)) {
        MongoInspector_supportedCollections[i][func] = orig[func];
      }
    }
    
  }
};
```

@krawalli nice update to the original wrapper. :+1:

**Comment by msavin** [comment]
Thanks for the great work gentlemen!

**Comment by msavin** [comment]
Thanks for the great work gentlemen! I've added you guys to the source code :)
