### ISSUE TITLE
Users Collection not shown

### ISSUE THREAD

**Issue by SantoshSrinivas79** [msavin/MongoInspector#17]
@msavin Any idea why the users collection is not shown in the inspector?

**Comment by msavin** [comment]
I believe because its privately namespaced under Meteor.

You're just in time for my new package though :)

http://mongol.meteor.com


On Feb 18, 2015, at 08:41 PM, fountainhead <notifications@github.com> wrote:

@msavin Any idea why the users collection is not shown in the inspector?

**Comment by fountainhead** [comment]
Still unable to get Meteor.users

My console shows 4 users when I type in `Meteor.users.find().fetch()` ... basically it is an output of a "search user" form

**Comment by msavin** [comment]
Pretty sure that data is not being published. You'd have to publish it manually if you want all the users. It could be beneficial to think if its a good idea.

On Feb 18, 2015, at 09:06 PM, fountainhead <notifications@github.com> wrote:

Still unable to get Meteor.users
My console shows 4 users when I type in Meteor.users.find().fetch() ... basically it is an output of a "search user" form

**Comment by fountainhead** [comment]
Not sure I'm understanding correctly. The data is being published and I can
see the published data in `Meteor.users.find().fetch() `. I can see the 4
users I published. But the inspector doesn't show them.

**Comment by krawalli** [comment]
check the position of the package in .meteor/packages

In most cases it should be near the top of the used packages. Otherwise MongoInspector is not "notified" that a collection exists and so it has nothing to show.

**Comment by msavin** [comment]
Krawalli - have you seen this? 
https://github.com/dburles/mongo-collection-instances

By the way, new package :)
http://mongol.meteor.com 

Code coming soon

**Comment by krawalli** [comment]
yeah, seen it on crater (and the funny title)
Gonna search for css errors once its released - so clean up the code carefully :)

For collection: yeah i know. There is another cool code. Check this: https://github.com/rclai/shadow-collection

**Comment by msavin** [comment]
Nice! Haha the pressure is on.

May have to give the two a try. I'm thinking of putting automatic detection as default, and manual as a back-up. 

Anyways, what do you do man? Can't hide behind the avatar forever :)

**Comment by krawalli** [comment]
Yes I can, wanna bet?

@fountainhead: sorry for hijacking your issue :)

**Comment by msavin** [comment]
@krawalli you're lucky I'm not a hacker! haha add me on Skype msavin5
@fountainhead double sorry

**Comment by krawalli** [comment]
I am a penguin. No msn, no skype, no windows.... only darkness :) 
*strange music starting in background*

**Comment by fountainhead** [comment]
Thanks @krawalli . Putting `msavin:mongoinspector` at the top shows all collections
