### ISSUE TITLE
debugOnly=true? I dont know 😖

### ISSUE THREAD

**Issue by comerc** [msavin/MongoInspector#5]
Please describe: how to use your package with debugOnly flag?

**Comment by Kestanous** [comment]
Would you consider changing that? This could be useful as an admin tool in production.

**Comment by msavin** [comment]
I'll think it through. 

PS: New package:
http://mongol.meteor.com

**Comment by Kestanous** [comment]
I followed that Github link but I did not see the actual package repo. After poking around this is the only package I could find, do you have it in a private repository?

**Comment by msavin** [comment]
I'm working on publishing the source code, I just want to tidy it up a little first. But the package works and can be used.

**Comment by Kestanous** [comment]
Cool. I will keep an eye out for it. Demo looks good! I just like to scan packages before I use them, too many moving parts and hacks out there right now.

**Comment by msavin** [comment]
I hear you - I'll try to get the code up soon. I can assure you everything is namespaced, so there shouldn't be any conflicts with your application code. 

On Feb 18, 2015, at 04:57 PM, Sivli Kestanous <notifications@github.com> wrote:

Cool. I will keep an eye out for it. Demo looks good! I just like to scan packages before I use them, too many moving parts and hacks out there right now.
