### ISSUE TITLE
getting started?

### ISSUE THREAD

**Issue by dcsan** [msavin/MongoInspector#7]
this looks great, but unfortunately the grey inspector window doesn't show up for me. is there anything i can check to see if it's installed correctly? i don't see any related output in the console at startup.

**Comment by msavin** [comment]
Ah - we have a new update now that will automatically detect Mongo collections now. Unfortunately, I can't tell what the issue is without seeing the code, but it sounds like there is an element with an unusually high z-index that is blocking out MongoInspector

**Comment by msavin** [comment]
Hey, I haven't heard back so I will assume you found the issue. I'll close the issue for now, but if you have any news let me know.
